name = "PlotlyExtensionsHelper"
uuid = "a7e57fc7-3548-4021-90c3-ac0e175068b1"
authors = ["Alberto Mengali <disberd@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
